
package bankingservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankingService", targetNamespace = "http://bankingservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankingService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payment", targetNamespace = "http://bankingservice/", className = "bankingservice.Payment")
    @ResponseWrapper(localName = "paymentResponse", targetNamespace = "http://bankingservice/", className = "bankingservice.PaymentResponse")
    @Action(input = "http://bankingservice/BankingService/paymentRequest", output = "http://bankingservice/BankingService/paymentResponse")
    public String payment(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
