
package bankingservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankingServiceImplService", targetNamespace = "http://bankingservice/", wsdlLocation = "http://localhost:8080/WS/BankingService?wsdl")
public class BankingServiceImplService
    extends Service
{

    private final static URL BANKINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKINGSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BANKINGSERVICEIMPLSERVICE_QNAME = new QName("http://bankingservice/", "BankingServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/BankingService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKINGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BANKINGSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BankingServiceImplService() {
        super(__getWsdlLocation(), BANKINGSERVICEIMPLSERVICE_QNAME);
    }

    public BankingServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public BankingServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BANKINGSERVICEIMPLSERVICE_QNAME);
    }

    public BankingServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public BankingServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankingServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankingService
     */
    @WebEndpoint(name = "BankingServiceImplPort")
    public BankingService getBankingServiceImplPort() {
        return super.getPort(new QName("http://bankingservice/", "BankingServiceImplPort"), BankingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankingService
     */
    @WebEndpoint(name = "BankingServiceImplPort")
    public BankingService getBankingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bankingservice/", "BankingServiceImplPort"), BankingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKINGSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BANKINGSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BANKINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
